-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 22:58:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ECommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ECommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ECommerce` DEFAULT CHARACTER SET utf8 ;
USE `ECommerce` ;

-- -----------------------------------------------------
-- Table `ECommerce`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommerce`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nomeFornecedor` VARCHAR(70) NOT NULL,
  `CNPJ` INT NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommerce`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `ECommerce`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommerce`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(100) NULL,
  `CPF` INT(11) NULL COMMENT 'CPF será obrigatório, caso CNPJ não seja informado.\nIsso será garantido por Check Constraint.',
  `CNPJ` INT(14) NULL COMMENT 'CNPJ será obrigatório, caso CPF não seja informado.\nIsso será garantido por Check Constraint.',
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Endereco_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommerce`.`Endereco_Cliente` (
  `idEndereco_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Logradouro` VARCHAR(100) NOT NULL,
  `Numero` INT NULL,
  `Complemento` VARCHAR(50) NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `Bairro` VARCHAR(70) NOT NULL,
  `Cidade` VARCHAR(70) NOT NULL,
  `Estado` VARCHAR(50) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEndereco_Cliente`, `Cliente_idCliente`),
  INDEX `fk_Endereco_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ECommerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommerce`.`Pedido` (
  `idPedido` INT NOT NULL,
  `dataPedido` DATE NOT NULL,
  `statusPedido` VARCHAR(20) NOT NULL COMMENT 'O status do pedido posicionará toda situação do mesmo até finalização da entrega.',
  `Endereco_Cliente_idEndereco_Cliente` INT NOT NULL,
  `Endereco_Cliente_Cliente_idCliente` INT NOT NULL,
  `dataPrazoDevolucao` DATE NULL COMMENT 'O prazo de devolução é uma regra de negócio que considera vários fatores. Portanto, o sistema fará o calculo do prazo e registrará esse dado neste campo do pedido.',
  `valorFrete` DECIMAL(5,2) NULL COMMENT 'O valor do frete será calculado pelo sistema e registrado neste campo. Esse calculo considera o endereço de entrega apontado no pedido informado pelo cliente e registrado no pedido.',
  `codigoRastreioEntrega` VARCHAR(50) NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Endereco_Cliente1_idx` (`Endereco_Cliente_idEndereco_Cliente` ASC, `Endereco_Cliente_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Endereco_Cliente1`
    FOREIGN KEY (`Endereco_Cliente_idEndereco_Cliente` , `Endereco_Cliente_Cliente_idCliente`)
    REFERENCES `ECommerce`.`Endereco_Cliente` (`idEndereco_Cliente` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Item_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommerce`.`Item_Pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quatidade` INT NOT NULL,
  `valorUnitario` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ECommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `ECommerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Meio_Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommerce`.`Meio_Pagamento` (
  `idMeio_Pagamento` INT NOT NULL AUTO_INCREMENT,
  `nomeMeio_Pagamento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idMeio_Pagamento`),
  UNIQUE INDEX `nomeMeio_Pagamento_UNIQUE` (`nomeMeio_Pagamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECommerce`.`Pagamento_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECommerce`.`Pagamento_Pedido` (
  `idPagamento_Pedido` INT NOT NULL AUTO_INCREMENT,
  `Pedido_idPedido` INT NOT NULL,
  `Meio_Pagamento_idMeio_Pagamento` INT NOT NULL,
  `valorPagamento` DECIMAL(10,2) NOT NULL COMMENT 'A validação da soma de todos as formas de pagamento com o total do pedido deverá ser validado pela aplicação.',
  `numeroParcelas` INT NOT NULL,
  PRIMARY KEY (`idPagamento_Pedido`),
  INDEX `fk_Meio_Pagamento_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Meio_Pagamento_has_Pedido_Meio_Pagamento1_idx` (`Meio_Pagamento_idMeio_Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Meio_Pagamento_has_Pedido_Meio_Pagamento1`
    FOREIGN KEY (`Meio_Pagamento_idMeio_Pagamento`)
    REFERENCES `ECommerce`.`Meio_Pagamento` (`idMeio_Pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Meio_Pagamento_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `ECommerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
